---
- name: Configure test PHP server
  hosts: test_server
  become: yes

  vars:
    project_root: /var/www/php_app
    server_name: testserver.local

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Install PHP and extensions
      apt:
        name:
          - php
          - php-cli
          - php-curl
          - php-zip
          - php-xml
          - php-mbstring
          - php-intl
          - libapache2-mod-php
        state: present

    - name: Enable Apache rewrite module
      command: a2enmod rewrite
      notify: Restart Apache

    - name: Create project directory
      file:
        path: "{{ project_root }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Deploy default index.php
      copy:
        dest: "{{ project_root }}/index.php"
        content: |
          <?php
          phpinfo();
          ?>

    - name: Disable default Apache website
      command: a2dissite 000-default.conf
      notify: Restart Apache

    - name: Create virtual host file
      copy:
        dest: /etc/apache2/sites-available/project.conf
        content: |
          <VirtualHost *:80>
              ServerName {{ server_name }}
              DocumentRoot {{ project_root }}

              <Directory {{ project_root }}>
                  AllowOverride All
                  Require all granted
              </Directory>

              ErrorLog ${APACHE_LOG_DIR}/project_error.log
              CustomLog ${APACHE_LOG_DIR}/project_access.log combined
          </VirtualHost>

    - name: Enable project site
      command: a2ensite project.conf
      notify: Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
